### ISSUE TITLE
AWS EKS OIDC Provider's `authorization_endpoint` is not URI 

### ISSUE THREAD

**Issue by sashaCher** [nov/openid_connect#62]
AWS [EKS OIDC Provider](https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html)'s `openid-configuration` is looking like this:
```json
{
  "issuer": "https://oidc.eks.us-east-2.amazonaws.com/id/EXAMPLED539D4633E53DE1B716D3041E",
  "jwks_uri": "https://oidc.eks.us-east-2.amazonaws.com/id/EXAMPLED539D4633E53DE1B716D3041E/keys",
  "authorization_endpoint": "urn:kubernetes:programmatic_authorization",
  "response_types_supported": [
    "id_token"
  ],
  "subject_types_supported": [
    "public"
  ],
  "claims_supported": [
    "sub",
    "iss"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ]
}
```
As you can see `authorization_endpoint` is not URI so discovery fails:
```
irb(main):001:0> require 'openid_connect'
=> true
irb(main):002:0> OpenIDConnect::Discovery::Provider::Config.discover!("hhttps://oidc.eks.us-east-2.amazonaws.com/id/EXAMPLED539D4633E53DE1B716D3041E")
Traceback (most recent call last):
        4: from /var/lib/ruby/bin/irb:11:in `<main>'
        3: from (irb):5
        2: from /var/lib/ruby/lib/ruby/gems/2.5.0/gems/openid_connect-1.2.0/lib/openid_connect/discovery/provider/config.rb:5:in `discover!'
        1: from /var/lib/ruby/lib/ruby/gems/2.5.0/gems/openid_connect-1.2.0/lib/openid_connect/discovery/provider/config.rb:12:in `rescue in discover!'
OpenIDConnect::Discovery::DiscoveryFailed (Authorization endpoint is not a valid URL)
```

**Comment by nov** [comment]
then it's out of scope of OAuth & OIDC, and this gem also won't support it.r
