### ISSUE TITLE
test failures with ruby 3.0

### ISSUE THREAD

**Issue by mdb571** [nov/openid_connect#72]
I'm getting the following error when running the tests with ruby 3.0 :
```
      Failure/Error:
        expect do
          klass.decode self_issued, :self_issued
        end.not_to raise_error
 
        expected no Exception, got #<OpenSSL::PKey::PKeyError: rsa#set_key= is incompatible with OpenSSL 3.0> with backtrace:
          # /usr/share/rubygems-integration/all/gems/json-jwt-1.13.0/lib/json/jwk.rb:106:in `set_key'
          # /usr/share/rubygems-integration/all/gems/json-jwt-1.13.0/lib/json/jwk.rb:106:in `to_rsa_key'
          # /usr/share/rubygems-integration/all/gems/json-jwt-1.13.0/lib/json/jwk.rb:43:in `to_key'
          # /usr/share/rubygems-integration/all/gems/json-jwt-1.13.0/lib/json/jose.rb:27:in `with_jwk_support'
          # /usr/share/rubygems-integration/all/gems/json-jwt-1.13.0/lib/json/jws.rb:124:in `valid?'
          # /usr/share/rubygems-integration/all/gems/json-jwt-1.13.0/lib/json/jws.rb:26:in `verify!'
          # ./lib/openid_connect/response_object/id_token.rb:79:in `decode_self_issued'
          # ./lib/openid_connect/response_object/id_token.rb:68:in `decode'
          # ./spec/openid_connect/response_object/id_token_spec.rb:263:in `block (7 levels) in <top (required)>'
          # ./spec/openid_connect/response_object/id_token_spec.rb:262:in `block (6 levels) in <top (required)>'
       # ./spec/openid_connect/response_object/id_token_spec.rb:262:in `block (6 levels) in <top (required)>'
  
 Finished in 13.15 seconds (files took 1.19 seconds to load)
 234 examples, 2 failures, 2 pending
 
 Failed examples:
 
 rspec ./spec/openid_connect/discovery/provider/config/response_spec.rb:98 # OpenIDConnect::Discovery::Provider::Config::Response#public_keys 
 rspec ./spec/openid_connect/response_object/id_token_spec.rb:261 # OpenIDConnect::ResponseObject::IdToken.decode when self-issued when valid when key == :self_issued is expected not to raise Exception

```

**Comment by mdb571** [comment]
Just noticed you have already released a newer version of json-jwt with support for openssl3 . Updating the json-jwt gem fixes this failure. Sorry for the noise
